### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by grlscz** [aurelia/route-recognizer#10]
Hi! I'm new to github and open source collaboration in general - sorry if this is the wrong place to ask.

Recently i got tired of waiting for usable declarations to appear (not having all "any") and started to work on them myself (using "rewrite-to typescript" approach based on https://github.com/cmichaelgraham/aurelia-ts-port). I'd like to contribute some of my results, if it is appropriate. Where do I start? Just make a pull request?

In the case of this particular module, the ways I see to improve the definitions:

1. Use `Dictionary<T>` instead of `Object`:
```
interface Dictionary<T> {  [key:string]:T; }

generateQueryString(params:Dictionary<string|string[]>):string
parseQueryString(queryString:string):Dictionary<string|string[]|boolean>
```

2. Use generic type for route handler:
```
interface HandlerEntry<T extends RouteHandler> {
  handler:T;
  names:string[];
}

export class RouteRecognizer<T extends RouteHandler>

recognize(path:string):RecognizeResults<T>
```

This would allow to avoid casting of results to handler class. At least in theory - since in router it is used with union-typed handler, and casting is needed anyway.

3. Return type of `recognize` method: it is not `RecognizedRoute[]`, it is `RecognizeResults` - which does have some properties of an array, but not the one. Also it has additional `queryParams` property which is actually used in router.

```
  recognize(path:string):RecognizeResults<T>

class RecognizeResults<T extends RouteHandler> implements ArrayLike<RecognizedRoute<T>> {
  splice: { (start: number): RecognizedRoute<T>[]; (start: number, deleteCount: number, ...items: RecognizedRoute<T>[]): RecognizedRoute<T>[] };
  slice: { (start?: number, end?: number): RecognizedRoute<T>[] };
  push: { (...items: RecognizedRoute<T>[]): number };
  [i: number]: RecognizedRoute<T>;
  length: number;
  queryParams: Dictionary<string|string[]|boolean>;
  constructor(queryParams:Object) {
    this.splice = Array.prototype.splice;
    this.slice = Array.prototype.slice;
    this.push = Array.prototype.push;
    this.length = 0;
    this.queryParams = queryParams || {};
  }
}
```

4. Return type of `add` - it is not pure `State`, it is augmented with additional properies. They might be irrelevant internal things, but the only use of return value of this method I found so far refers to one of these properties only, not to the `State` methods.

```
interface RouteState<T extends RouteHandler> {
  get(charSpec: CharSpec): RouteState<T>;
  put(charSpec: CharSpec): RouteState<T>;
  match(ch: string): RouteState<T>[];
  regex: RegExp;
  handlers: HandlerEntry<T>[];
  types: {
    statics: number;
    dynamics: number;
    stars: number;
  };
}

  add(route:ConfigurableRoute|ConfigurableRoute[]):RouteState<T>
```

**Comment by EisenbergEffect** [comment]
All libraries now have official d.ts files. If you would like to contribute, you can send PRs directly against the source.
