### ISSUE TITLE
`generate` should replace matching parent parameters rather than adding them to the query string

### ISSUE THREAD

**Issue by brantwedel** [aurelia/route-recognizer#11]
When navigating within a child router, it is not currently possible to re-set route params from the parent routes.

Example:
We have groups, with users. User management is a child route within groups context.
We have urls like this:

Group Route Config:
`{ route: 'groups/:groupId/users', module: './user-admin' }`

UserAdmin Child Router Config: 
`{ name: 'users-admin', route: '', module: './users-default' }`
`{ name: 'user-detail', route: ':userId', module: './user-detail' }`

ex urls:
`/groups/123/users/`
`/groups/123/users/1`

There is currently no simple way to generate a route to 'users-admin' or 'user-detail' with a different `:groupId` if using child routers as above.

In a child route, we might have a component that switches the parent 'group' context, but should remain at the `users-admin` route level.
ex navigating from:
`groups/123/users` to `groups/456/users`

Ideally this could be done using `router.generate('users-admin', { groupId: 456 })` but currently this generates the route:
`/groups/123/users/?groupId=456`
when it would ideally generate the route:
`/groups/456/users/`

Example Code:

``` js
export class App {
    configureRouter(config, router) {
        config.map([
            { route: '', moduleId: './welcome' },
            { route: 'groups/:groupId/items', moduleId: './group-items-master' },
        ]);
        this.router = router;
    }
}

@inject(Router)
export class GroupItemsMaster {
    constructor(router) {
        this.router = router;
    }
    configureRouter(config, router) {
        config.map([
            { name: 'item-default', route: '', moduleId: './item-default' },
            { name: 'item-detail', route: ':itemId', moduleId: './item-detail' },
        ]);
        this.router = router;
    }
    /* switch to another group */
    switchGroup(newGroupId) {
        // this, or something like this, should use the `/groups/:groupId/items` parent param
        // on the route/instruction instead of adding `?groupId=123` as a query string
        // maybe with a { mergeParams: true } option
        this.router.navigateToRoute('item-default', { groupId: newGroupId });
    }
}
```

Note:
This can almost be worked around by using flat routes, but then master-detail style view-models cannot be accomplished. ex:
`{ route: 'groups/:groupId/users/', module: './users-admin-default' }`
`{ route: 'groups/:groupId/users/:userId', module: './users-admin-item-detail' }`

**Comment by brantwedel** [comment]
Looking through the code again: I think something like this would need to be implemented in the router generate method rather than the recognizer, since router has the parent router/recognizer information. I am looking into making a PR and can move this issue to that repo if that sounds correct. https://github.com/aurelia/router/blob/master/src/router.js#L151

**Comment by bryanrsmith** [comment]
I agree. This was probably just an oversight when implementing the generation code. I think you're right that it will need to be handled by the router where we have access to the parent instruction. If you'd like to work on a PR that would be great!

**Comment by brantwedel** [comment]
@bryanrsmith: I think I have a plan to fix it, actually looks like there will need to be changes to router-recognizer generate, as well as router generate. I will look at it over the weekend.

Plan:
- Modify `RouteRecognizer::generate`, or add new method, to optionally output queryString, and return the 'consumed' route params  

    ```
    generate(name:string, params:Object, appendQueryParams?:boolean = true, consumed?:Array<string>):string
    ```
- Modify `Router::generate`, if child router, to recursively rewrite baseUrl segment only if `this.recognizer.generate(name, params, true, consumed)` did not consume all params. Then if recursive rewrites do not consume all params, add leftover params as query string.

**Comment by EisenbergEffect** [comment]
Did this get addressed? @brantwedel mentioned a plan to fix it but this was back in July...

**Comment by jsobell** [comment]
Perhaps if we had a karma test sample that demonstrated a child router that did *not* define its own baseURL someone might be able to jump in and help out :)
I looked at the tests but couldn't fathom out how to do this.  I couldn't see how to add the child router programmatically such that it honored the parent router as the prefixed base url.
Can anyone help with this so we can get this ancient bug sorted?

**Comment by gavinaiken** [comment]
This issue appears to be resolved in the latest release of aurelia. Not sure what change took care of it though.

**Comment by OzgurDogan** [comment]
I just recently updated my packages and getting this weird issue.

Updated to
`aurelia-route-recognizer@1.3.2,
aurelia-router@1.7.1`

Has anyone the same behavior with these packages?
