### ISSUE TITLE
Wildcards not recognized

### ISSUE THREAD

**Issue by BoudewijnvanVeen** [aurelia/route-recognizer#16]
I have the following wildcard in my aurelia route config:

```html
 route: 'access_token*path'...
```

I use this path as  redirect from an oauth owin authentication process. (using asp.net web.api).  This callback returns an acces key which is used to communicate authenticated with the webapi further on.

However the wildcard does not work as documented, because i get an error: "route nog recognized". After changing  [this](https://github.com/aurelia/route-recognizer/blob/master/src/route-recognizer.js#L247) to: 

```html
match = segment.match(/^.+[*]([^\/]+)$/)
```

It works for me. Dont know if i screwed things up now but it does the job.

**Comment by EisenbergEffect** [comment]
@bryansmith Can you investigate the regex change?

**Comment by bryansmith** [comment]
I think you would have meant your contributor bryanrsmith and not myself. By an amazing coincidence, my middle initial is also R - how weird (well 1 in 26 at least) is that. Good luck with your regex change.

**Comment by EisenbergEffect** [comment]
LOL Oops. @bryanrsmith Please see above ;)

**Comment by bryanrsmith** [comment]
Haha ;-)

@BoudewijnvanVeen Can you provide an example path that you're hoping to match? The current approach requires that segments start after a slash, so I'd expect `access_token/*path` to work.

**Comment by BoudewijnvanVeen** [comment]
@bryanrsmith: I am using route-recognizer 0.7.0. I am returning to Aurelia after an oauth login using the following redirect: 

```
http://localhost:4000/#access_token=ldLRqKrpbuoY_72AD_pQBLbzoe.....
```

I tried the following wildcard routes:

```
route: 'access_token*path',...  and
route: 'access_token/*path'
```

But both return "route not recognized.."

If i change the regex to the one mentioned in the first post it works as expected. The requested module is loaded and the 'path' segment is forwarded to the 'activate' event of the module.

**Comment by bryanrsmith** [comment]
Sorry for the delayed response, @BoudewijnvanVeen. The `*` is a special character at the beginning of a path segment that causes the segment to behave differently. We can't accept it at an arbitrary position in the segment at the moment.

If you want to capture the access token with a wildcard parameter you'll need a slash to separate the segments. With the URL you posted you'd need to use `route: '*path'`, and parse it yourself.

You probably want to either put the token in a query string parameter, or separate it with a slash.

```
 // would match http://localhost:4000/#access_token/ldLRqKrpbuoY_72AD_pQBLbzoe.....
route: 'access_token/*token'

// would match http://localhost:4000/#signin?access_token=ldLRqKrpbuoY_72AD_pQBLbzoe.....
// with `access_token` available in the `activate` params
route: 'signin'
```

**Comment by BoudewijnvanVeen** [comment]
@bryanrsmith thanks for the response Bryan. 

Concerning the solution you give me, this wil not work since i cannot and will not modify the format of the redirect uri of the oauth process. 

How ever i found another solution which recognizes the oauth redirect uri in a maybe more appropriate location, the _main.js aurelia start()_:

```
aurelia.start().then(() => {
    var auth = aurelia.container.get(authService);
    if (aurelia.host.baseURI.indexOf(baseConfig.tokenName)>-1) {
      auth.login();
    } else {
      let root = auth.isAuthenticated() ? 'app' : 'authentication/login';
      aurelia.setRoot(root);
    }
```

Thanks for your time and effort.

**Comment by bryanrsmith** [comment]
I see. Unfortunately the router wasn't designed to be able to match arbitrary patterns when you don't control the format of the URL. I do think you'll need to manually parse it in this case, which it looks like you've figured out. Glad you've got it working!
