### ISSUE TITLE
'respect explicit href during generation' causes generation error.

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [aurelia/route-recognizer#24]
@EisenbergEffect You added the following code in [this Commit](https://github.com/aurelia/route-recognizer/commit/335f2a7ecb927bc7f2bc68fa2462be1f353d8f55#diff-29a3c01cdede5f7d3f08a295e4c3abd4).

```
 +    let handler = route.handlers[0].handler;
 +    if (handler.href) {
 +      return handler.href;
 +    }

// generates path.
 ```

All code that generates path after the above *return handler.href* is ignored.

The following code has become showing *Route not found* error.  It's a serious matter for us.

```
route: 'Person-list/:model/:id',  href:'Person-list',  name:'Person-list', ....
```

```
    	this.router.navigateToRoute('Person-list', {model: 'Family', id: familyID }, {})

```

It works again if I remove the following code from aurelia-router.js and hrefs from route config.

```
          throw new Error('Invalid route config for "' + config.route + '" : dynamic routes must specify an "href:" to be included in the navigation model.');
```

**Comment by EisenbergEffect** [comment]
Why are you specifying an `href` on the route config? That is designed to override route generation for the nav model.

**Comment by HIRANO-Satoshi** [comment]
I don't understand why I need to have href. I think there is no explanation on it in the document.

My route config is like this. I commented out the *return handler.href;* to make this work.

```
{ route: 'Person-list/:model/:eID', href:  'Person-list', 
    moduleId: '../person/person-list', name: ' 'Person-list', title: 'Person List' },
```

Seems very ambiguous.

If I don't have the href, Aurelia shows an error like *Invalid route config for "/Person/:pID/:eID" : dynamic routes must specify an "href:" to be included in the navigation model.*

**Comment by EisenbergEffect** [comment]
Ok, so you are trying to include that in a navigation model. I don't see a `nav: true` property. Did you omit that from the sample?

**Comment by HIRANO-Satoshi** [comment]
Yes, I omitted.

**Comment by EisenbergEffect** [comment]
Ok, that makes sense then. Let me ponder this.
