### ISSUE TITLE
Error message when folder name is not matched correctly against moduleId I get a missleading error message

### ISSUE THREAD

**Issue by SatheesA** [aurelia/route-recognizer#27]
**I'm submitting a feature request**
- **Library Version:**
  major.minor.patch-pre

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  4.5.0
  
  
- **NPM Version:**
  3.10.8
- **Browser:**
  Chrome 53
- **Language:**
  ESNext

**Current behavior:**
When you have an uppercased letter in the routing settings like this:
`{
        route: ['', 'cards'],
        name: 'cards',
        moduleId: 'pages/cards/cards',
        nav: true,
        title: 'Cards'
      }`
And your folder is named "Pages" and not "pages" you get error which is not very user friendly and does not give you any hint about how/what to fix.:
`Uncaught SyntaxError: Unexpected token export
vendor-bundle.js:10830 Uncaught TypeError: Cannot read property '__useDefault' of undefined`

The problem was that the folder had the first letter uppercased while in the route I had written "pages"  in lowercase in moduleId.

**Expected/desired behavior:**
That it should give a more user friendly error message.
- **What is the motivation / use case for changing the behavior?**
  Might be a silly small thing but I used alot of time since I could not pick up anything good from google and didn't connect the error message to the problem.

**Comment by EisenbergEffect** [comment]
This relates to your module loader not being able to load the module that you specified. The problem is happening outside of Aurelia. The error is thrown by Aurelia though, but much lower down than the router. What module loader are you using? I would expect the browser's console to be showing  Not Found error in addition to this.

**Comment by SatheesA** [comment]
I'm using the standard loader from the Aurelia Cli RequireJS. I don't think the module loader is failing since one of the error is coming from cards.js which is the module it is trying to load.  I don't see any Not Found errors either. On the network tab the cards.js file is also loaded. here is the whole error from the console:
`cards.js:1 Uncaught SyntaxError: Unexpected token import
vendor-bundle.js:27850 Uncaught TypeError: Cannot read property '__useDefault' of undefinedensureOriginOnExports @ vendor-bundle.js:27850(anonymous function) @ vendor-bundle.js:27958execCb @ vendor-bundle.js:3785check @ vendor-bundle.js:3774(anonymous function) @ vendor-bundle.js:3778(anonymous function) @ vendor-bundle.js:3763(anonymous function) @ vendor-bundle.js:3779y @ vendor-bundle.js:3762emit @ vendor-bundle.js:3779check @ vendor-bundle.js:3775enable @ vendor-bundle.js:3779init @ vendor-bundle.js:3772I @ vendor-bundle.js:3769completeLoad @ vendor-bundle.js:3784onScriptLoad @ vendor-bundle.js:3785`

**Comment by EisenbergEffect** [comment]
It looks like there's some problem with your transpilation. It's definitely not something to do with Aurelia though.
