### ISSUE TITLE
`generate` should automatically add extra parameters to the query string

### ISSUE THREAD

**Issue by bryanrsmith** [aurelia/route-recognizer#3]
Given a route with name `'thing'` and path `'/things/:id'`, I should be able to use `recognizer.generate('thing', { id: 123, foo: 'bar' })` to generate `/things/123?foo=bar`. Currently, a caller must explicitly identify the parameters to be added to the query string, with `recognizer.generate('thing', { id: 123, queryParams: { foo: 'bar' } })`. As a consumer identifying a route by name, I shouldn't have to care where the parameters go. In my experience, this change would make the API more consistent with other routing libraries.

**Comment by EisenbergEffect** [comment]
That looks nice. Any interest in taking this on? (I did see the other PR....busy week this week...will get to that soon.)

**Comment by bryanrsmith** [comment]
Yes, definitely. I'm just starting to write some tests for this project, and reading code to figure out the API to be tested. I'll submit issues for possible improvements I find, and then circling back to work on them after there are enough tests to make sure I don't break other things :-)
