### ISSUE TITLE
Null reference error when optional parameter omitted from path

### ISSUE THREAD

**Issue by Jon-Hilton** [aurelia/route-recognizer#36]
**I'm submitting a bug report**

* **Library Version:**
1.2.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.11.1

* **NPM Version:**
5.6.0

* **JSPM OR Webpack AND Version**
webpack 3.6.0

* **Browser:**
all 

* **Language:**
TypeScript 2.9.2

**Current behavior:**
Given a route defined as follows:

``` javascript
{ route: 'batch/:partId/:batchNumber/:jobId/:tab?', settings: { auth: true, }, 
name: 'viewJob', moduleId: PLATFORM.moduleName('../job/job'), nav: false, title: 'View Job' }
```
            
Attempting to navigate to ```http://localhost:60233/batch/736/6354750``` results in an error.

**Unhandled rejection TypeError: Cannot read property '1' of null**

Which appears to be this code...

``` javascript
function findHandler(state, path, queryParams) {
  var handlers = state.handlers;
  var regex = state.regex;
  var captures = path.match(regex);
  var currentCapture = 1;
  var result = new RecognizeResults(queryParams);

  for (var i = 0, l = handlers.length; i < l; i++) {
    var _handler = handlers[i];
    var _names = _handler.names;
    var _params = {};

    for (var j = 0, m = _names.length; j < m; j++) {
      _params[_names[j]] = captures[currentCapture++];
    }

    result.push({ handler: _handler.handler, params: _params, isDynamic: !!_names.length });
  }

  return result;
}
```

Specifically this line...

``` _params[_names[j]] = captures[currentCapture++];```

Seems captures is null.

The relevant values (for this line ```var captures = path.match(regex);```) are:

path: ```/batch/736/6354750```
regex: ```^\/batch\/([^\/]+)\/([^\/]+)\/([^\/]+)(?:\/([^\/]+))?$```

**Expected/desired behavior:**

Seems to me that omitting the optional parameter (```:tab?```) should not cause the routing to fail with this error but to simply invoke the route anyway (minus the optional parameter)?

**Comment by Alexander-Taran** [comment]
@Jon-Hilton  Seems like you do not have a `jobId` specified in the link

**Comment by Jon-Hilton** [comment]
You know that thing where the answer's staring you in the face and you're somehow completely blind to it...

Yes of course that's it. 

Thanks for being another pair of eyes 👍
